require("../src/config/loadEnv");
require("./lib/stagingSafety").assertStagingMutationAllowed();
const assert = require("node:assert/strict");
const { randomBytes, randomUUID } = require("node:crypto");
const bcrypt = require("bcrypt");
const mongoose = require("mongoose");
const app = require("../src/app");
const { connectDatabase, disconnectDatabase } = require("../src/config/database");
const models = require("../src/models");

const runId = randomUUID(); const marker = runId.slice(0, 8); const password = `Tn-${randomBytes(18).toString("base64url")}9aA`; const ids = {}; const tokens = {}; let server; let apiBase; let adminId; const organizationIds = []; const opportunityIds = [];
const trustedIn = (values) => mongoose.trusted({ $in: values });
const call = async (path, { method = "GET", token, body } = {}) => { const response = await fetch(`${apiBase}${path}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); const text = await response.text(); let payload; try { payload = JSON.parse(text); } catch (_error) { payload = { text }; } return { status: response.status, payload }; };
const register = async (label) => { const response = await call("/auth/register", { method: "POST", body: { email: `phase8-${marker}-${label}@example.invalid`, password, role: "freelancer", profile: { firstName: "P8", lastName: label } } }); assert.equal(response.status, 201, JSON.stringify(response.payload)); ids[label] = response.payload.data.user.id; tokens[label] = response.payload.data.accessToken; await call("/profile", { method: "PUT", token: tokens[label], body: { username: `p8-${label}-${marker}`, headline: "Early-career platform engineer", location: "Bengaluru, India", visibility: "public", availability: "open", discoverable: true } }); };
const opportunityBody = (organizationId, skillId, suffix, overrides = {}) => ({ organizationId, type: "internship", title: `Platform Engineering Intern ${suffix}`, slug: `platform-intern-${suffix.toLowerCase()}-${marker}`, summary: "Build reliable product systems with a small platform team.", description: "A structured internship for early-career engineers.", responsibilities: ["Ship tested API improvements", "Document operational decisions"], requirements: ["Current undergraduate student", "Comfort with JavaScript"], workMode: "hybrid", locations: [{ city: "Bengaluru", country: "India", display: "Bengaluru, India" }], employmentType: "full_time", duration: "6 months", compensation: { minAmount: 40000, maxAmount: 60000, currency: "INR", period: "month" }, applicationUrl: `https://careers.example.com/${suffix.toLowerCase()}`, applicationDeadline: new Date(Date.now() + 30 * 86400000).toISOString(), requiredSkillIds: [skillId], preferredSkillIds: [], eligibility: { eligibleDegrees: ["B.Tech"], eligibleFields: ["Computer Science"], graduationYearMin: 2026, graduationYearMax: 2028, allowedCountries: ["India"], finalYearAllowed: true, freshersAllowed: true }, sourceType: "official", sourceUrl: "https://careers.example.com", sourcePublishedAt: new Date().toISOString(), ...overrides });
const createDraft = async (orgId, skillId, suffix, overrides) => { const response = await call("/admin/opportunities", { method: "POST", token: tokens.admin, body: opportunityBody(orgId, skillId, suffix, overrides) }); assert.equal(response.status, 201, JSON.stringify(response.payload)); opportunityIds.push(response.payload.data.id); return response.payload.data; };
const publish = async (draft) => { const response = await call(`/admin/opportunities/${draft.id}/publish`, { method: "POST", token: tokens.admin, body: { revision: draft.revision } }); assert.equal(response.status, 200, JSON.stringify(response.payload)); return response.payload.data; };
const cleanup = async () => { const users = trustedIn([...Object.values(ids), adminId].filter(Boolean)); const opportunities = trustedIn(opportunityIds); await models.OpportunityCandidateState.deleteMany({ $or: mongoose.trusted([{ opportunity_id: opportunities }, { user_id: users }]) }); await models.Opportunity.deleteMany({ _id: opportunities }); await models.Organization.deleteMany({ _id: trustedIn(organizationIds) }); await Promise.all([models.UserSkill.deleteMany({ user_id: users }), models.UserEducation.deleteMany({ user_id: users }), models.UserProfile.deleteMany({ _id: users }), models.AuditLog.deleteMany({ user_id: users }), models.User.deleteMany({ _id: users })]); };

const run = async () => {
  await connectDatabase(); for (const Model of [models.Organization, models.Opportunity, models.OpportunityCandidateState]) await Model.syncIndexes(); server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); apiBase = `http://127.0.0.1:${server.address().port}/api`;
  try {
    await Promise.all([register("candidate"), register("second")]); adminId = randomUUID(); await models.User.create({ _id: adminId, email: `phase8-${marker}-admin@example.invalid`, password: await bcrypt.hash(password, 4), role: "admin", profile: { firstName: "P8", lastName: "Admin" }, status: "active" }); await models.UserProfile.create({ _id: adminId, username: `p8-admin-${marker}`, visibility: "private", availability: "unavailable" }); const login = await call("/auth/login", { method: "POST", body: { email: `phase8-${marker}-admin@example.invalid`, password } }); assert.equal(login.status, 200); tokens.admin = login.payload.data.accessToken;
    const skill = await models.Skill.findOne({ is_active: true }).lean(); assert.ok(skill, "Seeded skill catalog is required"); await models.UserSkill.create({ _id: randomUUID(), user_id: ids.candidate, skill_id: skill._id, proficiency: "intermediate", is_primary: true }); await models.UserEducation.create({ _id: randomUUID(), user_id: ids.candidate, institution: "Verification Institute", degree_course: "B.Tech", field_of_study: "Computer Science", start_year: 2023, end_year: 2027 });
    const orgCreate = await call("/admin/organizations", { method: "POST", token: tokens.admin, body: { name: `Phase 8 Labs ${marker}`, slug: `phase8-labs-${marker}`, organizationType: "startup", tagline: "Reliable systems for real work.", description: "A fixture Organization used only for Phase 8 acceptance.", websiteUrl: "https://example.com", industry: "Developer tools", headquarters: { city: "Bengaluru", country: "India" } } }); assert.equal(orgCreate.status, 201, JSON.stringify(orgCreate.payload)); const org = orgCreate.payload.data; organizationIds.push(org.id);
    assert.equal((await call("/admin/organizations", { method: "POST", token: tokens.candidate, body: { name: "Forbidden", slug: `forbidden-${marker}`, organizationType: "company" } })).status, 403, "Non-admin catalog write must fail"); const verified = await call(`/admin/organizations/${org.id}/verify`, { method: "POST", token: tokens.admin, body: { revision: org.revision, verified: true } }); assert.equal(verified.status, 200); assert.equal(verified.payload.data.verification_status, "verified");
    const draft = await createDraft(org.id, skill._id, "Main"); assert.equal((await call(`/opportunities/${draft.slug}`)).status, 404, "Draft must not be public"); const main = await publish(draft);
    const publicList = await call(`/opportunities?type=internship&workMode=hybrid&location=Bengaluru&skills=${skill._id}&graduationYear=2027&freshersAllowed=true&compensationDisclosed=true&search=Platform`); assert.equal(publicList.status, 200); assert.ok(publicList.payload.data.some((row) => row.id === main.id)); assert.equal(Object.hasOwn(publicList.payload.data.find((row) => row.id === main.id), "eligibility"), false, "Anonymous eligibility must not be exposed");
    const candidateList = await call(`/opportunities?type=internship&skills=${skill._id}`, { token: tokens.candidate }); const candidateRole = candidateList.payload.data.find((row) => row.id === main.id); assert.equal(candidateRole.eligibility.result, "eligible"); assert.equal(Object.hasOwn(candidateRole.eligibility, "score"), false); const detail = await call(`/opportunities/${main.slug}`, { token: tokens.candidate }); assert.equal(detail.status, 200); assert.equal(detail.payload.data.application_url.startsWith("https://"), true); assert.equal(detail.payload.data.created_by, undefined);
    const saves = await Promise.all([call(`/opportunities/${main.id}/save`, { method: "POST", token: tokens.candidate }), call(`/opportunities/${main.id}/save`, { method: "POST", token: tokens.candidate })]); assert.ok(saves.every((row) => [201, 409].includes(row.status))); assert.equal(await models.OpportunityCandidateState.countDocuments({ opportunity_id: main.id, user_id: ids.candidate }), 1, "Duplicate save race must create one state");
    const initialApps = await Promise.all([call(`/opportunities/${main.id}/application`, { method: "PUT", token: tokens.second, body: { status: "applied", notes: "Applied externally" } }), call(`/opportunities/${main.id}/application`, { method: "PUT", token: tokens.second, body: { status: "applied" } })]); assert.equal(initialApps.filter((row) => row.status === 200).length, 1, "Duplicate application race must have one winner"); const initial = initialApps.find((row) => row.status === 200).payload.data; assert.equal(await models.OpportunityCandidateState.countDocuments({ opportunity_id: main.id, user_id: ids.second, application_status: "applied" }), 1);
    const revisions = await Promise.all([call(`/opportunities/${main.id}/application`, { method: "PUT", token: tokens.second, body: { status: "assessment", revision: initial.revision } }), call(`/opportunities/${main.id}/application`, { method: "PUT", token: tokens.second, body: { status: "interview", revision: initial.revision } })]); assert.deepEqual(revisions.map((row) => row.status).sort(), [200, 409], "Application revision race must have one CAS winner");
    const editRaceDraft = await createDraft(org.id, skill._id, "EditRace"); const publishEdit = await Promise.all([call(`/admin/opportunities/${editRaceDraft.id}/publish`, { method: "POST", token: tokens.admin, body: { revision: editRaceDraft.revision } }), call(`/admin/opportunities/${editRaceDraft.id}`, { method: "PATCH", token: tokens.admin, body: { revision: editRaceDraft.revision, summary: "A concurrent catalog edit." } })]); assert.deepEqual(publishEdit.map((row) => row.status).sort(), [200, 409], "Publish versus edit must have one CAS winner");
    const closeDraft = await createDraft(org.id, skill._id, "CloseRace"); const closeRole = await publish(closeDraft); const closeSave = await Promise.all([call(`/admin/opportunities/${closeRole.id}/close`, { method: "POST", token: tokens.admin, body: { revision: closeRole.revision } }), call(`/opportunities/${closeRole.id}/save`, { method: "POST", token: tokens.second })]); assert.equal(closeSave.find((row) => row.status === 200)?.payload.data.status, "closed"); const closedState = await models.OpportunityCandidateState.findOne({ opportunity_id: closeRole.id, user_id: ids.second }).lean(); if (closeSave.find((row) => row.status === 201)) assert.ok(closedState?.saved, "A save ordered before close must remain historical"); else assert.equal(closedState, null, "A close ordered first must reject the new save");
    const closedMain = await call(`/admin/opportunities/${main.id}/close`, { method: "POST", token: tokens.admin, body: { revision: main.revision } }); assert.equal(closedMain.status, 200); const afterClose = await call(`/opportunities/${main.id}/application`, { method: "PUT", token: tokens.second, body: { status: "interview", revision: revisions.find((row) => row.status === 200).payload.data.revision } }); assert.equal(afterClose.status, 200, "Existing candidate history must remain updatable after close"); const applications = await call("/applications", { token: tokens.second }); assert.ok(applications.payload.data.some((row) => row.opportunity.id === main.id), "Closed historical application must remain visible"); assert.equal((await call(`/opportunities/${main.id}/save`, { method: "POST", token: tokens.candidate })).status, 409, "Closed Opportunity must reject a new save action");
    const plans = await Promise.all([models.Opportunity.find({ type: "internship", status: "published" }).sort({ published_at: -1 }).explain("queryPlanner"), models.Opportunity.find({ organization_id: org.id, status: "published" }).sort({ published_at: -1 }).explain("queryPlanner"), models.OpportunityCandidateState.find({ user_id: ids.second, application_status: "interview" }).sort({ updated_at: -1 }).explain("queryPlanner"), models.OpportunityCandidateState.find({ user_id: ids.candidate, saved: true }).sort({ updated_at: -1 }).explain("queryPlanner")]); plans.forEach((plan) => assert.match(JSON.stringify(plan.queryPlanner?.winningPlan || {}), /IXSCAN/));
    process.stdout.write("Phase 8 Opportunity verification passed: controlled Organization/catalog API, public discovery/filtering, deterministic eligibility, external apply provenance, candidate privacy, duplicate/CAS races, close ordering, retained history, indexes, and Atlas query plans.\n");
  } finally { await cleanup(); }
};
run().catch((error) => { process.stderr.write(`Phase 8 Opportunity verification failed: ${error.stack || error.message}\n`); process.exitCode = 1; }).finally(async () => { if (server) await new Promise((resolve) => server.close(resolve)); await disconnectDatabase(); });
