-- TaskNexus SQL Schema for Supabase/PostgreSQL
-- This schema is migrated from the original Mongoose design.
--
-- Decisions:
-- 1. UUIDs for Primary Keys: Using `uuid` generated by `gen_random_uuid()` for primary keys for global uniqueness.
-- 2. JSONB for Nested Objects: Using `jsonb` for semi-structured data like profiles, details, etc. It's efficient and flexible.
-- 3. ENUM Types: Creating custom ENUM types for fields like 'role', 'status', etc., to enforce data integrity.
-- 4. Foreign Keys: Establishing foreign key relationships to maintain relational integrity.
-- 5. Indexes: Replicating the indexes from the Mongoose schema for query performance.

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ENUM Types
CREATE TYPE user_role AS ENUM ('client', 'freelancer', 'admin');
CREATE TYPE user_status AS ENUM ('active', 'suspended', 'blocked');
CREATE TYPE freelancer_availability AS ENUM ('full-time', 'part-time', 'weekends', 'flexible');
CREATE TYPE task_status AS ENUM (
  'submitted', 'under_review', 'assigned', 'in_progress', 'submitted_work',
  'qa_review', 'revision_requested', 'delivered', 'client_revision',
  'completed', 'cancelled', 'disputed'
);
CREATE TYPE task_type AS ENUM ('video-editing', 'web-development', 'design', 'writing', 'other');
CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE submission_type AS ENUM ('initial', 'revision');
CREATE TYPE qa_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE client_review_status AS ENUM ('pending', 'approved', 'revision_requested');
CREATE TYPE payment_status AS ENUM ('pending', 'escrowed', 'released', 'refunded');
CREATE TYPE review_type AS ENUM ('client_to_platform', 'platform_to_freelancer');
CREATE TYPE notification_type AS ENUM (
  'task_assigned', 'task_submitted', 'qa_feedback', 'client_approval',
  'revision_requested', 'payment_released', 'deadline_reminder'
);
CREATE TYPE notification_status AS ENUM ('unread', 'read');
CREATE TYPE notification_priority AS ENUM ('low', 'medium', 'high');
CREATE TYPE resource_type AS ENUM ('user', 'task', 'submission', 'payment', 'review', 'notification', 'settings');

-- Users Table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role user_role NOT NULL,
  profile JSONB NOT NULL,
  freelancer_profile JSONB,
  client_profile JSONB,
  status user_status NOT NULL DEFAULT 'active',
  refresh_token TEXT,
  last_login TIMESTAMPTZ,
  is_email_verified BOOLEAN NOT NULL DEFAULT false,
  password_reset_token TEXT,
  password_reset_expires TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_freelancer_performance ON users USING GIN ((freelancer_profile->'performanceScore'));

-- Tasks Table
CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id TEXT NOT NULL UNIQUE,
  client_id UUID NOT NULL REFERENCES users(id),
  freelancer_id UUID REFERENCES users(id),
  assigned_by_id UUID REFERENCES users(id),
  task_details JSONB NOT NULL,
  status task_status NOT NULL DEFAULT 'submitted',
  workflow JSONB,
  metrics JSONB,
  priority task_priority NOT NULL DEFAULT 'medium',
  tags TEXT[],
  admin_notes TEXT,
  cancellation_reason TEXT,
  dispute JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tasks_client_id ON tasks(client_id);
CREATE INDEX idx_tasks_freelancer_id ON tasks(freelancer_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_deadline ON tasks USING GIN ((task_details->'deadline'));

-- Submissions Table
CREATE TABLE submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id),
  freelancer_id UUID NOT NULL REFERENCES users(id),
  submission_type submission_type NOT NULL,
  content JSONB NOT NULL,
  qa_review JSONB,
  client_review JSONB,
  version INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_submissions_task_id ON submissions(task_id);
CREATE INDEX idx_submissions_freelancer_id ON submissions(freelancer_id);

-- Payments Table
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id TEXT NOT NULL UNIQUE,
  task_id UUID NOT NULL REFERENCES tasks(id),
  client_id UUID NOT NULL REFERENCES users(id),
  freelancer_id UUID NOT NULL REFERENCES users(id),
  amounts JSONB NOT NULL,
  status payment_status NOT NULL DEFAULT 'pending',
  escrow JSONB,
  transaction_details JSONB,
  refund JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_task_id ON payments(task_id);
CREATE INDEX idx_payments_client_id ON payments(client_id);
CREATE INDEX idx_payments_freelancer_id ON payments(freelancer_id);
CREATE INDEX idx_payments_status ON payments(status);

-- Reviews Table
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id),
  reviewer_id UUID NOT NULL REFERENCES users(id),
  reviewee_id UUID NOT NULL REFERENCES users(id),
  review_type review_type NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback TEXT,
  is_public BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(task_id, reviewer_id, review_type)
);
CREATE INDEX idx_reviews_task_id ON reviews(task_id);
CREATE INDEX idx_reviews_reviewer_id ON reviews(reviewer_id);
CREATE INDEX idx_reviews_reviewee_id ON reviews(reviewee_id);

-- Notifications Table
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id UUID NOT NULL REFERENCES users(id),
  type notification_type NOT NULL,
  content JSONB NOT NULL,
  related_task_id UUID REFERENCES tasks(id),
  status notification_status NOT NULL DEFAULT 'unread',
  priority notification_priority NOT NULL DEFAULT 'medium',
  read_at TIMESTAMPTZ,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX idx_notifications_status ON notifications(status);

-- Audit Logs Table
CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  action TEXT NOT NULL,
  resource resource_type NOT NULL,
  resource_id UUID,
  changes JSONB,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource, resource_id);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp);
