-- TaskNexus SQL Schema for Supabase/PostgreSQL
-- This schema is the canonical PostgreSQL design for the current data layer.
--
-- Decisions:
-- 1. UUIDs for Primary Keys: Using `uuid` generated by `gen_random_uuid()` for primary keys for global uniqueness.
-- 2. JSONB for Nested Objects: Using `jsonb` for semi-structured data like profiles, details, etc. It's efficient and flexible.
-- 3. ENUM Types: Creating custom ENUM types for fields like 'role', 'status', etc., to enforce data integrity.
-- 4. Foreign Keys: Establishing foreign key relationships to maintain relational integrity.
-- 5. Indexes: Replicating the indexes from the Mongoose schema for query performance.

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ENUM Types
CREATE TYPE user_role AS ENUM ('client', 'freelancer', 'admin');
CREATE TYPE user_status AS ENUM ('active', 'suspended', 'blocked');
CREATE TYPE freelancer_availability AS ENUM ('available', 'part_time', 'busy');
CREATE TYPE task_status AS ENUM (
  'submitted', 'under_review', 'assigned', 'in_progress', 'submitted_work',
  'qa_review', 'revision_requested', 'delivered', 'client_revision',
  'completed', 'cancelled', 'disputed'
);
CREATE TYPE task_type AS ENUM (
  'video-editing', 'web-development', 'mobile-development', 'design',
  'writing', 'marketing', 'data-entry', 'other'
);
CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE submission_type AS ENUM ('initial', 'revision');
CREATE TYPE qa_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE client_review_status AS ENUM ('pending', 'approved', 'revision_requested');
CREATE TYPE payment_status AS ENUM ('pending', 'escrowed', 'released', 'refunded');
CREATE TYPE review_type AS ENUM ('client_to_platform', 'platform_to_freelancer');
CREATE TYPE notification_type AS ENUM (
  'task_assigned', 'task_submitted', 'qa_feedback', 'client_approval',
  'revision_requested', 'payment_released', 'deadline_reminder',
  'task_cancelled', 'dispute_raised', 'account_warning', 'task_started',
  'task_unaccepted', 'task_progress', 'submission_updated',
  'account_status_changed', 'task_approved', 'task_rejected',
  'submission_approved', 'new_review'
);
CREATE TYPE notification_status AS ENUM ('unread', 'read');
CREATE TYPE notification_priority AS ENUM ('low', 'medium', 'high');
CREATE TYPE resource_type AS ENUM (
  'user', 'task', 'submission', 'payment', 'review', 'notification', 'settings',
  'newsletter_subscription', 'service_booking', 'support_jar_contribution'
);

-- Users Table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role user_role NOT NULL,
  profile JSONB NOT NULL,
  freelancer_profile JSONB,
  client_profile JSONB,
  status user_status NOT NULL DEFAULT 'active',
  refresh_token TEXT,
  last_login TIMESTAMPTZ,
  is_email_verified BOOLEAN NOT NULL DEFAULT false,
  password_reset_token TEXT,
  password_reset_expires TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_freelancer_performance ON users USING GIN ((freelancer_profile->'performanceScore'));

-- Tasks Table
CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id TEXT NOT NULL UNIQUE,
  client_id UUID NOT NULL REFERENCES users(id),
  freelancer_id UUID REFERENCES users(id),
  assigned_by_id UUID REFERENCES users(id),
  task_details JSONB NOT NULL,
  status task_status NOT NULL DEFAULT 'submitted',
  workflow JSONB,
  metrics JSONB,
  priority task_priority NOT NULL DEFAULT 'medium',
  tags TEXT[],
  admin_notes TEXT,
  cancellation_reason TEXT,
  dispute JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tasks_client_id ON tasks(client_id);
CREATE INDEX idx_tasks_freelancer_id ON tasks(freelancer_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_deadline ON tasks USING GIN ((task_details->'deadline'));

-- Submissions Table
CREATE TABLE submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id),
  freelancer_id UUID NOT NULL REFERENCES users(id),
  submission_type submission_type NOT NULL,
  content JSONB NOT NULL,
  qa_review JSONB,
  client_review JSONB,
  version INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  idempotency_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_submissions_task_id ON submissions(task_id);
CREATE INDEX idx_submissions_freelancer_id ON submissions(freelancer_id);
CREATE UNIQUE INDEX idx_submissions_idempotency_key ON submissions(freelancer_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Payments Table
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id TEXT NOT NULL UNIQUE,
  task_id UUID NOT NULL REFERENCES tasks(id),
  client_id UUID NOT NULL REFERENCES users(id),
  freelancer_id UUID NOT NULL REFERENCES users(id),
  amounts JSONB NOT NULL,
  status payment_status NOT NULL DEFAULT 'pending',
  escrow JSONB,
  transaction_details JSONB,
  refund JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_task_id ON payments(task_id);
CREATE INDEX idx_payments_client_id ON payments(client_id);
CREATE INDEX idx_payments_freelancer_id ON payments(freelancer_id);
CREATE INDEX idx_payments_status ON payments(status);

-- Reviews Table
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id),
  reviewer_id UUID NOT NULL REFERENCES users(id),
  reviewee_id UUID NOT NULL REFERENCES users(id),
  review_type review_type NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback TEXT,
  is_public BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(task_id, reviewer_id, review_type)
);
CREATE INDEX idx_reviews_task_id ON reviews(task_id);
CREATE INDEX idx_reviews_reviewer_id ON reviews(reviewer_id);
CREATE INDEX idx_reviews_reviewee_id ON reviews(reviewee_id);

-- Notifications Table
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id UUID NOT NULL REFERENCES users(id),
  actor_id UUID REFERENCES users(id),
  type notification_type NOT NULL,
  content JSONB NOT NULL,
  related_task_id UUID REFERENCES tasks(id),
  entity_type TEXT,
  entity_id UUID,
  status notification_status NOT NULL DEFAULT 'unread',
  priority notification_priority NOT NULL DEFAULT 'medium',
  read_at TIMESTAMPTZ,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX idx_notifications_status ON notifications(status);
CREATE INDEX idx_notifications_actor_id ON notifications(actor_id);
CREATE INDEX idx_notifications_related_task_id ON notifications(related_task_id);

-- Newsletter Subscriptions Table
CREATE TABLE newsletter_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL DEFAULT 'blog',
  status TEXT NOT NULL DEFAULT 'subscribed',
  brevo_contact_id BIGINT,
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_newsletter_subscriptions_email ON newsletter_subscriptions(email);
CREATE INDEX idx_newsletter_subscriptions_status ON newsletter_subscriptions(status);

-- Service Bookings Table
CREATE TABLE service_bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT NOT NULL UNIQUE,
  session_id TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  service_slug TEXT NOT NULL,
  service_snapshot JSONB NOT NULL,
  preferred_date DATE NOT NULL,
  preferred_time TEXT NOT NULL,
  timezone TEXT NOT NULL,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'requested',
  email_status TEXT NOT NULL DEFAULT 'pending',
  brevo_message_ids JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_service_bookings_booking_id ON service_bookings(booking_id);
CREATE INDEX idx_service_bookings_email ON service_bookings(email);
CREATE INDEX idx_service_bookings_status ON service_bookings(status);

-- Support Jar Contributions Table
CREATE TABLE support_jar_contributions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  currency TEXT NOT NULL,
  message TEXT,
  email_status TEXT NOT NULL DEFAULT 'pending',
  brevo_message_ids JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_support_jar_contributions_email ON support_jar_contributions(email);
CREATE INDEX idx_support_jar_contributions_created_at ON support_jar_contributions(created_at);

-- Audit Logs Table
CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  action TEXT NOT NULL,
  resource resource_type NOT NULL,
  resource_id UUID,
  changes JSONB,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource, resource_id);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp);

-- High-contention collaboration data is normalized to avoid lost JSONB updates.
CREATE TABLE task_comments (
  id TEXT PRIMARY KEY,
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  author_id UUID REFERENCES users(id),
  author_name TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  mentions JSONB NOT NULL DEFAULT '[]'::jsonb,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE task_milestones (
  id TEXT PRIMARY KEY,
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  due_at TIMESTAMPTZ,
  weight NUMERIC NOT NULL DEFAULT 0 CHECK (weight >= 0 AND weight <= 100),
  completed BOOLEAN NOT NULL DEFAULT false,
  completed_at TIMESTAMPTZ,
  completed_by UUID REFERENCES users(id),
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE task_activity (
  id TEXT PRIMARY KEY,
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,
  actor_id UUID REFERENCES users(id),
  actor_name TEXT NOT NULL,
  message TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_task_comments_task_created ON task_comments(task_id, created_at);
CREATE INDEX idx_task_comments_author_id ON task_comments(author_id);
CREATE INDEX idx_task_milestones_task_position ON task_milestones(task_id, position, created_at);
CREATE INDEX idx_task_milestones_completed_by ON task_milestones(completed_by);
CREATE INDEX idx_task_activity_task_created ON task_activity(task_id, created_at);
CREATE INDEX idx_task_activity_actor_id ON task_activity(actor_id);
CREATE INDEX idx_tasks_assigned_by_id ON tasks(assigned_by_id);
CREATE INDEX idx_tasks_client_status_updated ON tasks(client_id, status, updated_at DESC);
CREATE INDEX idx_tasks_freelancer_status_updated ON tasks(freelancer_id, status, updated_at DESC);
CREATE INDEX idx_tasks_available_updated ON tasks(status, updated_at DESC) WHERE freelancer_id IS NULL;
CREATE INDEX idx_notifications_recipient_status_created ON notifications(recipient_id, status, created_at DESC);

CREATE OR REPLACE FUNCTION accept_task(p_task_id UUID, p_freelancer_id UUID)
RETURNS SETOF tasks
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE tasks
  SET freelancer_id = p_freelancer_id,
      status = 'assigned',
      workflow = jsonb_set(COALESCE(workflow, '{}'::jsonb), '{assignedAt}', to_jsonb(now()), true),
      updated_at = now()
  WHERE id = p_task_id AND status = 'under_review' AND freelancer_id IS NULL
  RETURNING *;
$$;

REVOKE ALL ON FUNCTION accept_task(UUID, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION accept_task(UUID, UUID) TO service_role;

CREATE OR REPLACE FUNCTION submit_task_work(
  p_task_id UUID, p_freelancer_id UUID, p_content JSONB,
  p_submission_type submission_type, p_idempotency_key TEXT
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE existing_submission submissions%ROWTYPE;
DECLARE submitted_task tasks%ROWTYPE;
DECLARE created_submission submissions%ROWTYPE;
BEGIN
  SELECT * INTO existing_submission FROM submissions
  WHERE task_id = p_task_id
    AND freelancer_id = p_freelancer_id
    AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    SELECT * INTO submitted_task FROM tasks WHERE id = existing_submission.task_id;
    RETURN jsonb_build_object('task', to_jsonb(submitted_task), 'submission', to_jsonb(existing_submission));
  END IF;
  UPDATE tasks SET status = 'delivered',
    workflow = jsonb_set(COALESCE(workflow, '{}'::jsonb), '{deliveredAt}', to_jsonb(now()), true),
    updated_at = now()
  WHERE id = p_task_id AND freelancer_id = p_freelancer_id AND status = 'in_progress'
  RETURNING * INTO submitted_task;
  IF NOT FOUND THEN RETURN NULL; END IF;
  UPDATE submissions SET is_active = false WHERE task_id = p_task_id AND is_active = true;
  INSERT INTO submissions(task_id, freelancer_id, submission_type, content, version, is_active, idempotency_key)
  VALUES (p_task_id, p_freelancer_id, p_submission_type, p_content,
    COALESCE((SELECT MAX(version) + 1 FROM submissions WHERE task_id = p_task_id), 1), true, p_idempotency_key)
  RETURNING * INTO created_submission;
  RETURN jsonb_build_object('task', to_jsonb(submitted_task), 'submission', to_jsonb(created_submission));
END $$;

-- Phase 2 normalized professional profile baseline.
-- TaskNexus V2 Phase 2: canonical professional profiles.
-- The application continues to use a backend-only data-access model. Legacy
-- profile JSON is retained and selectively backfilled into normalized tables.

DO $$ BEGIN
  CREATE TYPE profile_visibility AS ENUM ('public', 'private');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE profile_availability AS ENUM ('open', 'limited', 'unavailable');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE collaboration_commitment AS ENUM ('exploring', 'few_hours', 'part_time', 'full_time');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE skill_proficiency AS ENUM ('beginner', 'intermediate', 'advanced');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  username TEXT,
  headline VARCHAR(120),
  bio VARCHAR(2000),
  avatar_url TEXT,
  location VARCHAR(120),
  timezone VARCHAR(80),
  availability profile_availability NOT NULL DEFAULT 'unavailable',
  collaboration_commitment collaboration_commitment NOT NULL DEFAULT 'exploring',
  github_url TEXT,
  linkedin_url TEXT,
  portfolio_url TEXT,
  interests TEXT[] NOT NULL DEFAULT '{}',
  preferred_roles TEXT[] NOT NULL DEFAULT '{}',
  visibility profile_visibility NOT NULL DEFAULT 'private',
  onboarding_completed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_username_format CHECK (
    username IS NULL OR username ~ '^[a-z][a-z0-9_-]{2,29}$'
  ),
  CONSTRAINT user_profiles_username_reserved CHECK (
    username IS NULL OR username <> ALL (ARRAY[
      'admin', 'api', 'app', 'auth', 'blog', 'dashboard', 'help', 'login',
      'logout', 'me', 'profile', 'register', 'root', 'security', 'settings',
      'support', 'system', 'tasknexus', 'tasks', 'team', 'teams', 'u', 'users'
    ])
  ),
  CONSTRAINT user_profiles_interests_limit CHECK (cardinality(interests) <= 12),
  CONSTRAINT user_profiles_roles_limit CHECK (cardinality(preferred_roles) <= 8),
  CONSTRAINT user_profiles_avatar_url_safe CHECK (avatar_url IS NULL OR avatar_url ~ '^https://'),
  CONSTRAINT user_profiles_github_url_safe CHECK (github_url IS NULL OR github_url ~ '^https://'),
  CONSTRAINT user_profiles_linkedin_url_safe CHECK (linkedin_url IS NULL OR linkedin_url ~ '^https://'),
  CONSTRAINT user_profiles_portfolio_url_safe CHECK (portfolio_url IS NULL OR portfolio_url ~ '^https://')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_username_ci
  ON user_profiles(lower(username)) WHERE username IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_profiles_public_username
  ON user_profiles(lower(username)) WHERE visibility = 'public' AND username IS NOT NULL;

CREATE TABLE IF NOT EXISTS skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL,
  name VARCHAR(80) NOT NULL,
  category VARCHAR(40) NOT NULL,
  aliases TEXT[] NOT NULL DEFAULT '{}',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT skills_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT skills_category_valid CHECK (category = ANY (ARRAY[
    'languages', 'frontend', 'backend', 'mobile', 'database', 'data-ai',
    'cloud-devops', 'design', 'product', 'quality', 'collaboration', 'other'
  ]))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_skills_slug_ci ON skills(lower(slug));
CREATE UNIQUE INDEX IF NOT EXISTS idx_skills_name_ci ON skills(lower(name));
CREATE INDEX IF NOT EXISTS idx_skills_category_name ON skills(category, name);
CREATE INDEX IF NOT EXISTS idx_skills_aliases ON skills USING GIN(aliases);

CREATE TABLE IF NOT EXISTS user_skills (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  skill_id UUID NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
  proficiency skill_proficiency NOT NULL DEFAULT 'intermediate',
  is_primary BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, skill_id)
);

CREATE INDEX IF NOT EXISTS idx_user_skills_skill_id ON user_skills(skill_id);
CREATE INDEX IF NOT EXISTS idx_user_skills_primary ON user_skills(user_id, is_primary) WHERE is_primary;

CREATE TABLE IF NOT EXISTS user_education (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  institution VARCHAR(160) NOT NULL,
  degree_course VARCHAR(160) NOT NULL,
  field_of_study VARCHAR(160),
  start_year SMALLINT NOT NULL,
  end_year SMALLINT,
  currently_studying BOOLEAN NOT NULL DEFAULT false,
  description VARCHAR(1000),
  position SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_education_start_year CHECK (start_year BETWEEN 1900 AND 2100),
  CONSTRAINT user_education_end_year CHECK (end_year IS NULL OR end_year BETWEEN 1900 AND 2100),
  CONSTRAINT user_education_year_order CHECK (end_year IS NULL OR end_year >= start_year),
  CONSTRAINT user_education_current_end CHECK (NOT currently_studying OR end_year IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_user_education_user_position
  ON user_education(user_id, position, start_year DESC);

INSERT INTO skills (slug, name, category, aliases) VALUES
  ('javascript', 'JavaScript', 'languages', ARRAY['js', 'ecmascript']),
  ('typescript', 'TypeScript', 'languages', ARRAY['ts']),
  ('python', 'Python', 'languages', ARRAY['python3']),
  ('java', 'Java', 'languages', ARRAY[]::TEXT[]),
  ('c-sharp', 'C#', 'languages', ARRAY['csharp', '.net c#']),
  ('go', 'Go', 'languages', ARRAY['golang']),
  ('rust', 'Rust', 'languages', ARRAY[]::TEXT[]),
  ('react', 'React', 'frontend', ARRAY['reactjs', 'react.js']),
  ('next-js', 'Next.js', 'frontend', ARRAY['nextjs', 'next']),
  ('vue-js', 'Vue.js', 'frontend', ARRAY['vue', 'vuejs']),
  ('angular', 'Angular', 'frontend', ARRAY['angularjs']),
  ('tailwind-css', 'Tailwind CSS', 'frontend', ARRAY['tailwind']),
  ('html-css', 'HTML & CSS', 'frontend', ARRAY['html', 'css', 'html5', 'css3']),
  ('node-js', 'Node.js', 'backend', ARRAY['node', 'nodejs']),
  ('express-js', 'Express.js', 'backend', ARRAY['express', 'expressjs']),
  ('django', 'Django', 'backend', ARRAY[]::TEXT[]),
  ('fastapi', 'FastAPI', 'backend', ARRAY['fast api']),
  ('spring-boot', 'Spring Boot', 'backend', ARRAY['spring']),
  ('graphql', 'GraphQL', 'backend', ARRAY['graphql api']),
  ('rest-apis', 'REST APIs', 'backend', ARRAY['rest', 'restful api']),
  ('react-native', 'React Native', 'mobile', ARRAY['react-native']),
  ('flutter', 'Flutter', 'mobile', ARRAY['dart flutter']),
  ('ios-development', 'iOS Development', 'mobile', ARRAY['ios', 'swiftui']),
  ('android-development', 'Android Development', 'mobile', ARRAY['android', 'kotlin android']),
  ('postgresql', 'PostgreSQL', 'database', ARRAY['postgres', 'psql']),
  ('mysql', 'MySQL', 'database', ARRAY[]::TEXT[]),
  ('mongodb', 'MongoDB', 'database', ARRAY['mongo']),
  ('supabase', 'Supabase', 'database', ARRAY[]::TEXT[]),
  ('redis', 'Redis', 'database', ARRAY[]::TEXT[]),
  ('machine-learning', 'Machine Learning', 'data-ai', ARRAY['ml']),
  ('data-analysis', 'Data Analysis', 'data-ai', ARRAY['analytics']),
  ('generative-ai', 'Generative AI', 'data-ai', ARRAY['genai', 'llm']),
  ('aws', 'Amazon Web Services', 'cloud-devops', ARRAY['amazon web services']),
  ('azure', 'Microsoft Azure', 'cloud-devops', ARRAY['azure cloud']),
  ('google-cloud', 'Google Cloud', 'cloud-devops', ARRAY['gcp']),
  ('docker', 'Docker', 'cloud-devops', ARRAY['containers']),
  ('kubernetes', 'Kubernetes', 'cloud-devops', ARRAY['k8s']),
  ('ci-cd', 'CI/CD', 'cloud-devops', ARRAY['continuous integration']),
  ('figma', 'Figma', 'design', ARRAY[]::TEXT[]),
  ('ui-ux-design', 'UI/UX Design', 'design', ARRAY['ux', 'ui design', 'product design']),
  ('product-management', 'Product Management', 'product', ARRAY['product manager']),
  ('project-management', 'Project Management', 'product', ARRAY['project manager']),
  ('automated-testing', 'Automated Testing', 'quality', ARRAY['test automation', 'qa automation']),
  ('technical-writing', 'Technical Writing', 'collaboration', ARRAY['documentation']),
  ('mentoring', 'Mentoring', 'collaboration', ARRAY['coaching'])
ON CONFLICT DO NOTHING;

INSERT INTO user_profiles (
  user_id, headline, bio, avatar_url, location, availability,
  github_url, linkedin_url, portfolio_url
)
SELECT
  u.id,
  NULLIF(trim(u.freelancer_profile->>'title'), ''),
  NULLIF(trim(u.freelancer_profile->>'bio'), ''),
  CASE WHEN u.profile->>'avatar' ~ '^https://' THEN u.profile->>'avatar' ELSE NULL END,
  NULLIF(trim(COALESCE(u.profile->>'location', u.freelancer_profile->>'location')), ''),
  CASE COALESCE(u.freelancer_profile->>'availability', '')
    WHEN 'available' THEN 'open'::profile_availability
    WHEN 'part_time' THEN 'limited'::profile_availability
    ELSE 'unavailable'::profile_availability
  END,
  CASE WHEN u.freelancer_profile->>'github' ~ '^https://' THEN u.freelancer_profile->>'github' ELSE NULL END,
  CASE WHEN u.freelancer_profile->>'linkedin' ~ '^https://' THEN u.freelancer_profile->>'linkedin' ELSE NULL END,
  CASE WHEN COALESCE(u.freelancer_profile->>'portfolio', u.freelancer_profile->>'website') ~ '^https://'
    THEN COALESCE(u.freelancer_profile->>'portfolio', u.freelancer_profile->>'website') ELSE NULL END
FROM users u
ON CONFLICT (user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION initialize_user_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  INSERT INTO user_profiles (user_id) VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS users_initialize_profile ON users;
CREATE TRIGGER users_initialize_profile
AFTER INSERT ON users
FOR EACH ROW EXECUTE FUNCTION initialize_user_profile();

WITH legacy AS (
  SELECT DISTINCT u.id AS user_id, trim(value) AS raw_name
  FROM users u
  CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE WHEN jsonb_typeof(u.freelancer_profile->'skills') = 'array'
      THEN u.freelancer_profile->'skills' ELSE '[]'::jsonb END
  ) value
  WHERE trim(value) <> ''
), unmatched AS (
  SELECT lower(regexp_replace(regexp_replace(raw_name, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')) AS slug,
         min(raw_name) AS raw_name
  FROM legacy l
  WHERE NOT EXISTS (
    SELECT 1 FROM skills s
    WHERE lower(s.name) = lower(l.raw_name)
       OR lower(s.slug) = lower(l.raw_name)
       OR lower(l.raw_name) = ANY(s.aliases)
  )
  GROUP BY lower(regexp_replace(regexp_replace(raw_name, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g'))
)
INSERT INTO skills (slug, name, category, aliases)
SELECT slug, left(raw_name, 80), 'other', ARRAY[lower(raw_name)]
FROM unmatched
WHERE slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
ON CONFLICT DO NOTHING;

WITH legacy AS (
  SELECT DISTINCT u.id AS user_id, trim(value) AS raw_name
  FROM users u
  CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE WHEN jsonb_typeof(u.freelancer_profile->'skills') = 'array'
      THEN u.freelancer_profile->'skills' ELSE '[]'::jsonb END
  ) value
  WHERE trim(value) <> ''
), resolved AS (
  SELECT DISTINCT ON (l.user_id, l.raw_name) l.user_id, s.id AS skill_id
  FROM legacy l
  JOIN skills s ON lower(s.name) = lower(l.raw_name)
    OR lower(s.slug) = lower(l.raw_name)
    OR lower(l.raw_name) = ANY(s.aliases)
  ORDER BY l.user_id, l.raw_name, s.name
)
INSERT INTO user_skills (user_id, skill_id, proficiency, is_primary)
SELECT user_id, skill_id, 'intermediate', false FROM resolved
ON CONFLICT (user_id, skill_id) DO NOTHING;

CREATE OR REPLACE FUNCTION replace_user_skills(p_user_id UUID, p_skills JSONB)
RETURNS SETOF user_skills
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE item_count INTEGER;
DECLARE valid_count INTEGER;
BEGIN
  IF jsonb_typeof(p_skills) <> 'array' THEN
    RAISE EXCEPTION 'skills must be a JSON array' USING ERRCODE = '22023';
  END IF;

  item_count := jsonb_array_length(p_skills);
  IF item_count > 30 THEN
    RAISE EXCEPTION 'a profile may contain at most 30 skills' USING ERRCODE = '22023';
  END IF;

  IF (SELECT count(DISTINCT item->>'skillId') FROM jsonb_array_elements(p_skills) item) <> item_count THEN
    RAISE EXCEPTION 'duplicate skills are not allowed' USING ERRCODE = '23505';
  END IF;

  IF (SELECT count(*) FROM jsonb_array_elements(p_skills) item
      WHERE COALESCE((item->>'isPrimary')::boolean, false)) > 5 THEN
    RAISE EXCEPTION 'a profile may contain at most 5 primary skills' USING ERRCODE = '22023';
  END IF;

  SELECT count(*) INTO valid_count
  FROM jsonb_array_elements(p_skills) item
  JOIN skills s ON s.id = (item->>'skillId')::uuid AND s.is_active;
  IF valid_count <> item_count THEN
    RAISE EXCEPTION 'one or more skills are invalid' USING ERRCODE = '22023';
  END IF;

  PERFORM 1 FROM users WHERE id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'user not found' USING ERRCODE = 'P0002';
  END IF;

  DELETE FROM user_skills WHERE user_id = p_user_id;
  RETURN QUERY
  INSERT INTO user_skills (user_id, skill_id, proficiency, is_primary)
  SELECT
    p_user_id,
    (item->>'skillId')::uuid,
    COALESCE(item->>'proficiency', 'intermediate')::skill_proficiency,
    COALESCE((item->>'isPrimary')::boolean, false)
  FROM jsonb_array_elements(p_skills) item
  RETURNING *;
END $$;

REVOKE ALL ON FUNCTION replace_user_skills(UUID, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION replace_user_skills(UUID, JSONB) TO service_role;

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['user_profiles', 'skills', 'user_skills', 'user_education']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM anon, authenticated', table_name);
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE ON TABLE user_profiles TO service_role;
GRANT SELECT ON TABLE skills TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_skills TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_education TO service_role;

-- Canonical skill search resolves catalog aliases and bounds every response.
CREATE OR REPLACE FUNCTION search_skills(
  p_query TEXT DEFAULT '', p_category TEXT DEFAULT NULL, p_limit INTEGER DEFAULT 20
)
RETURNS SETOF skills
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public
AS $$
  SELECT s.* FROM skills s
  WHERE s.is_active
    AND (p_category IS NULL OR p_category = '' OR s.category = p_category)
    AND (
      trim(COALESCE(p_query, '')) = ''
      OR s.name ILIKE '%' || trim(p_query) || '%'
      OR s.slug ILIKE '%' || trim(p_query) || '%'
      OR EXISTS (
        SELECT 1 FROM unnest(s.aliases) alias
        WHERE alias ILIKE '%' || trim(p_query) || '%'
      )
    )
  ORDER BY CASE WHEN lower(s.name) = lower(trim(COALESCE(p_query, ''))) THEN 0 ELSE 1 END, s.name
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 30);
$$;

REVOKE ALL ON FUNCTION search_skills(TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION search_skills(TEXT, TEXT, INTEGER) TO service_role;

INSERT INTO skills (slug, name, category, aliases) VALUES
  ('git', 'Git', 'cloud-devops', ARRAY['version control']),
  ('github', 'GitHub', 'collaboration', ARRAY['github actions', 'github workflows']),
  ('cybersecurity', 'Cybersecurity', 'quality', ARRAY['information security', 'appsec'])
ON CONFLICT DO NOTHING;



REVOKE ALL ON FUNCTION submit_task_work(UUID, UUID, JSONB, submission_type, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION submit_task_work(UUID, UUID, JSONB, submission_type, TEXT) TO service_role;

-- This is a backend-only application: browser database roles have no table access.
DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users', 'tasks', 'submissions', 'payments', 'reviews', 'notifications',
    'newsletter_subscriptions', 'service_bookings', 'support_jar_contributions',
    'audit_logs', 'task_comments', 'task_milestones', 'task_activity'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM anon, authenticated', table_name);
  END LOOP;
END $$;
