import { ExternalLink, Github, Loader2, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import { useAuth } from "../../context/AuthContext";
import api from "../../services/api";
import { apiError } from "../../utils/teams";
import { formatDate } from "../../utils/projects";

const labels = {
  project_participation: "Participation", project_role: "Project role", project_task_completion: "Task completion",
  github_commit: "GitHub commit", github_pull_request: "GitHub pull request", external_link: "External link",
};

const ContributionsPanel = ({ project, items = [], summary = {}, onChanged }) => {
  const { user } = useAuth();
  const [form, setForm] = useState({ type: "github_commit", title: "", sourceUrl: "", summary: "" });
  const [adding, setAdding] = useState(false); const [busy, setBusy] = useState("");
  const ownParticipant = project.participants?.find((item) => item.user_id === user?.id);
  const add = async (event) => {
    event.preventDefault(); setAdding(true);
    try { await api.post(`/projects/${project.id}/evidence`, form); toast.success("Evidence added as an explicit claim"); setForm({ type: "github_commit", title: "", sourceUrl: "", summary: "" }); await onChanged(); }
    catch (error) { toast.error(apiError(error)); } finally { setAdding(false); }
  };
  const verify = async (id) => { setBusy(id); try { await api.post(`/contribution-evidence/${id}/verify`); toast.success("GitHub authorship verified"); await onChanged(); } catch (error) { toast.error(apiError(error)); } finally { setBusy(""); } };
  const remove = async (id) => { setBusy(id); try { await api.delete(`/contribution-evidence/${id}`); toast.success("Evidence removed from active history"); await onChanged(); } catch (error) { toast.error(apiError(error)); } finally { setBusy(""); } };
  const toggleProfile = async () => { try { await api.patch(`/projects/${project.id}/profile-visibility`, { showOnProfile: !ownParticipant.show_on_profile }); toast.success("Profile visibility updated"); await onChanged(); } catch (error) { toast.error(apiError(error)); } };
  return <section className="space-y-6">
    <header className="flex flex-col gap-4 border-b border-[#23252a] pb-6 md:flex-row md:items-end md:justify-between"><div><p className="team-eyebrow">Evidence, not scores</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em]">Project contributions</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8a8f98]">Every entry retains its source, verification state, date, and project context. Counts summarize facts; they do not rank people.</p></div>{ownParticipant ? <button type="button" onClick={toggleProfile} className="team-button-secondary">{ownParticipant.show_on_profile ? "Shown on profile" : "Show published project on profile"}</button> : null}</header>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Internal facts" value={summary.by_verification?.internal_verified || 0} /><Metric label="GitHub verified" value={summary.by_verification?.external_verified || 0} /><Metric label="Unverified claims" value={summary.by_verification?.unverified || 0} /></div>
    {ownParticipant ? <form onSubmit={add} className="rounded-xl border border-[#23252a] bg-[#0f1011] p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-[#828fff]" /><h3 className="font-medium">Add external evidence</h3></div><p className="mt-2 text-xs leading-5 text-[#62666d]">GitHub items begin unverified. Verification requires a linked repository and a matching GitHub profile URL.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><label><span className="team-label">Type</span><select className="team-input" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="github_commit">GitHub commit</option><option value="github_pull_request">GitHub pull request</option><option value="external_link">External link</option></select></label><label><span className="team-label">Title</span><input required minLength="2" maxLength="180" className="team-input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label className="md:col-span-2"><span className="team-label">HTTPS evidence URL</span><input required type="url" className="team-input" placeholder="https://github.com/owner/repo/commit/..." value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} /></label><label className="md:col-span-2"><span className="team-label">Context</span><textarea maxLength="1000" className="team-input min-h-24 resize-y" value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} /></label></div><div className="mt-4 flex justify-end"><button disabled={adding} className="team-button-primary">{adding ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />} Add evidence</button></div></form> : null}
    <div className="space-y-3">{items.map((item) => <EvidenceCard key={item.id} item={item} own={item.user_id === user?.id} busy={busy === item.id} onVerify={() => verify(item.id)} onRemove={() => remove(item.id)} />)}{!items.length ? <div className="rounded-xl border border-dashed border-[#34343a] px-5 py-12 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-[#62666d]" /><p className="mt-3 text-sm text-[#8a8f98]">No contribution evidence has been recorded yet.</p></div> : null}</div>
  </section>;
};

const EvidenceCard = ({ item, own, busy, onVerify, onRemove }) => <article className="rounded-xl border border-[#23252a] bg-[#0f1011] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`evidence-badge is-${item.verification}`}>{item.verification.replaceAll("_", " ")}</span><span className="team-chip">{labels[item.type] || item.type}</span>{item.status !== "active" ? <span className="team-chip">{item.status}</span> : null}</div><h3 className="mt-3 break-words font-medium text-[#f7f8f8]">{item.title}</h3><p className="mt-1 text-sm text-[#8a8f98]">{item.participant?.display_name || "TaskNexus participant"} · {formatDate(item.occurred_at)}</p>{item.summary ? <p className="mt-3 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-[#8a8f98]">{item.summary}</p> : null}</div><div className="flex shrink-0 flex-wrap gap-2">{item.source_url ? <a className="team-icon-button" href={item.source_url} target="_blank" rel="noreferrer" aria-label="Open evidence source"><ExternalLink className="h-4 w-4" /></a> : null}{own && item.origin === "user" && item.provider === "github" && item.verification !== "external_verified" ? <button disabled={busy} onClick={onVerify} className="team-button-secondary">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Github className="h-4 w-4" />} Verify</button> : null}{own && item.origin === "user" ? <button disabled={busy} onClick={onRemove} className="team-icon-button" aria-label="Remove evidence"><Trash2 className="h-4 w-4" /></button> : null}</div></div><details className="mt-4 border-t border-[#23252a] pt-4 text-xs text-[#62666d]"><summary className="cursor-pointer select-none text-[#8a8f98]">Inspect provenance</summary><dl className="mt-3 grid gap-2 sm:grid-cols-2"><Detail label="Origin" value={item.origin === "system" ? "TaskNexus system event" : "Participant claim"} /><Detail label="Verification" value={item.verification.replaceAll("_", " ")} /><Detail label="Evidence ID" value={item.id} /><Detail label="Verified at" value={item.verified_at ? formatDate(item.verified_at) : "Not verified"} /></dl></details></article>;
const Detail = ({ label, value }) => <div><dt>{label}</dt><dd className="mt-0.5 break-all text-[#d0d6e0]">{value}</dd></div>;
const Metric = ({ label, value }) => <div className="rounded-xl border border-[#23252a] bg-[#0f1011] p-4"><p className="text-xs text-[#62666d]">{label}</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em]">{value}</p></div>;

export default ContributionsPanel;
