import { ArrowRight, Loader2, X } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import Dialog from "../common/Dialog";
import api from "../../services/api";
import { apiError } from "../../utils/teams";
import ProjectSkillPicker from "./ProjectSkillPicker";

const initial = { name: "", slug: "", tagline: "", description: "", visibility: "team", targetDate: "", repositoryUrl: "", demoUrl: "", tags: "" };

const CreateProjectDialog = ({ team, onClose, onCreated }) => {
  const [form, setForm] = useState(initial); const [skills, setSkills] = useState([]); const [saving, setSaving] = useState(false); const [slugEdited, setSlugEdited] = useState(false);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const name = (value) => setForm((current) => ({ ...current, name: value, ...(!slugEdited ? { slug: value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") } : {}) }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const response = await api.post(`/teams/${team.id}/projects`, { ...form, targetDate: form.targetDate || null, repositoryUrl: form.repositoryUrl || null, demoUrl: form.demoUrl || null, tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean), skillIds: skills.map((skill) => skill.id) }); toast.success("Project created"); onCreated(response.data.data); } catch (error) { toast.error(apiError(error, "Project could not be created")); } finally { setSaving(false); } };
  return <Dialog onClose={onClose} titleId="create-project-title" descriptionId="create-project-copy" panelClassName="max-w-3xl !border-[#34343a] !bg-[#0f1011] !shadow-none"><form onSubmit={submit} className="p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="team-eyebrow">New project · {team.name}</p><h2 id="create-project-title" className="mt-1 text-2xl font-semibold tracking-[-0.03em] text-[#f7f8f8]">Turn the team into a workspace.</h2><p id="create-project-copy" className="mt-2 text-sm leading-6 text-[#8a8f98]">Define what you are building. Participants and tasks come next.</p></div><button type="button" onClick={onClose} className="team-icon-button" aria-label="Close"><X className="h-4 w-4" /></button></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field required label="Project name" value={form.name} onChange={name} maxLength={100} /><Field required label="Slug" value={form.slug} onChange={(value) => { setSlugEdited(true); set("slug", value.toLowerCase().replace(/[^a-z0-9-]/g, "")); }} maxLength={70} /><div className="sm:col-span-2"><Field label="Tagline" value={form.tagline} onChange={(value) => set("tagline", value)} maxLength={180} placeholder="A precise description of the outcome" /></div><label className="sm:col-span-2"><span className="team-label">Description</span><textarea className="team-input min-h-28 resize-y" value={form.description} onChange={(event) => set("description", event.target.value)} maxLength={5000} /></label><label><span className="team-label">Visibility</span><select className="team-input" value={team.visibility === "private" ? "team" : form.visibility} disabled={team.visibility === "private"} onChange={(event) => set("visibility", event.target.value)}><option value="team">Team only</option><option value="public">Public summary</option></select></label><Field label="Target date" type="date" value={form.targetDate} onChange={(value) => set("targetDate", value)} /><div className="sm:col-span-2"><ProjectSkillPicker value={skills} onChange={setSkills} disabled={saving} /></div><Field label="Repository URL" type="url" value={form.repositoryUrl} onChange={(value) => set("repositoryUrl", value)} placeholder="https://github.com/..." /><Field label="Demo URL" type="url" value={form.demoUrl} onChange={(value) => set("demoUrl", value)} placeholder="https://..." /><div className="sm:col-span-2"><Field label="Tags" value={form.tags} onChange={(value) => set("tags", value)} placeholder="open-source, accessibility" /></div></div><div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="team-button-secondary">Cancel</button><button disabled={saving} className="team-button-primary">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />} Create project</button></div></form></Dialog>;
};

const Field = ({ label, value, onChange, ...props }) => <label><span className="team-label">{label}</span><input {...props} value={value} onChange={(event) => onChange(event.target.value)} className="team-input" /></label>;

export default CreateProjectDialog;
