import { CheckCircle2, ExternalLink, Github, Loader2, Plus, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import toast from "react-hot-toast";
import api from "../../services/api";
import { apiError } from "../../utils/teams";

const RepositorySettings = ({ projectId }) => {
  const [items, setItems] = useState([]); const [url, setUrl] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { try { const response = await api.get(`/projects/${projectId}/repositories`); setItems(response.data.data || []); } catch (error) { toast.error(apiError(error)); } }, [projectId]);
  useEffect(() => { load(); }, [load]);
  const add = async (event) => { event.preventDefault(); setBusy("add"); try { await api.post(`/projects/${projectId}/repositories`, { url }); setUrl(""); toast.success("GitHub repository linked"); await load(); } catch (error) { toast.error(apiError(error)); } finally { setBusy(""); } };
  const verify = async (id) => { setBusy(id); try { await api.post(`/projects/${projectId}/repositories/${id}/verify`); toast.success("Public GitHub repository verified"); await load(); } catch (error) { toast.error(apiError(error)); } finally { setBusy(""); } };
  const remove = async (id) => { setBusy(id); try { await api.delete(`/projects/${projectId}/repositories/${id}`); toast.success("Repository link removed"); await load(); } catch (error) { toast.error(apiError(error)); } finally { setBusy(""); } };
  return <section className="mt-6 rounded-xl border border-[#23252a] bg-[#0f1011] p-5 sm:p-7"><div className="flex items-center gap-2"><Github className="h-4 w-4 text-[#828fff]" /><h2 className="text-lg font-medium">Linked GitHub repositories</h2></div><p className="mt-2 text-sm leading-6 text-[#8a8f98]">Managers link public repositories here. TaskNexus constructs read-only GitHub API requests from the parsed owner and repository; arbitrary hosts are rejected.</p><form onSubmit={add} className="mt-5 flex flex-col gap-2 sm:flex-row"><label className="min-w-0 flex-1"><span className="sr-only">GitHub repository URL</span><input required type="url" placeholder="https://github.com/owner/repository" className="team-input" value={url} onChange={(event) => setUrl(event.target.value)} /></label><button disabled={Boolean(busy)} className="team-button-primary"><Plus className="h-4 w-4" /> Link repository</button></form><div className="mt-5 divide-y divide-[#23252a]">{items.map((item) => <article key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><a href={item.url} target="_blank" rel="noreferrer" className="inline-flex max-w-full items-center gap-2 truncate text-sm font-medium hover:text-[#b7bdf8]">{item.owner}/{item.repository}<ExternalLink className="h-3.5 w-3.5 shrink-0" /></a><p className="mt-1 flex items-center gap-1.5 text-xs text-[#62666d]">{item.verification_status === "verified" ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" /> : null}{item.verification_status.replaceAll("_", " ")}</p></div><div className="flex gap-2">{item.verification_status !== "verified" ? <button type="button" disabled={Boolean(busy)} onClick={() => verify(item.id)} className="team-button-secondary">{busy === item.id ? <Loader2 className="h-4 w-4 animate-spin" /> : null} Verify</button> : null}<button type="button" disabled={Boolean(busy)} onClick={() => remove(item.id)} className="team-icon-button" aria-label={`Remove ${item.owner}/${item.repository}`}><Trash2 className="h-4 w-4" /></button></div></article>)}{!items.length ? <p className="py-5 text-sm text-[#62666d]">No repositories linked.</p> : null}</div></section>;
};
export default RepositorySettings;
