import { Bookmark, Briefcase as BriefcaseBusiness, CalendarClock, MapPin } from "lucide-react";
import { Link } from "react-router-dom";
import { ELIGIBILITY_LABELS, OPPORTUNITY_TYPE_LABELS, WORK_MODE_LABELS, compensationLabel, formatDate, locationLabel } from "../../utils/opportunities";

const OpportunityCard = ({ opportunity, onSave, busy = false }) => {
  const location = opportunity.work_mode === "remote" ? "Remote" : locationLabel(opportunity.locations?.[0]) || "Location published on detail";
  return <article className="team-card flex min-w-0 flex-col"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="team-avatar">{opportunity.organization?.logo_url ? <img src={opportunity.organization.logo_url} alt="" className="h-full w-full rounded-xl object-cover" /> : (opportunity.organization?.name || "O").slice(0, 2).toUpperCase()}</div><div className="min-w-0"><Link to={`/organizations/${opportunity.organization?.slug}`} className="truncate text-xs text-[#828fff] hover:text-[#b7bdf8]">{opportunity.organization?.name}</Link><h2 className="mt-1 line-clamp-2 text-lg font-semibold tracking-[-0.025em]">{opportunity.title}</h2></div></div>{onSave ? <button type="button" disabled={busy} aria-label={opportunity.viewer_state?.saved ? "Remove saved Opportunity" : "Save Opportunity"} aria-pressed={Boolean(opportunity.viewer_state?.saved)} onClick={() => onSave(opportunity)} className={`team-icon-button ${opportunity.viewer_state?.saved ? "border-[#5e6ad2] text-[#b7bdf8]" : ""}`}><Bookmark className={`h-4 w-4 ${opportunity.viewer_state?.saved ? "fill-current" : ""}`} /></button> : null}</div><p className="mt-4 line-clamp-2 text-sm leading-6 text-[#8a8f98]">{opportunity.summary || "Review the role details and employer-published requirements."}</p><dl className="mt-5 grid gap-2 text-xs text-[#8a8f98]"><Info icon={BriefcaseBusiness} value={`${OPPORTUNITY_TYPE_LABELS[opportunity.type]} · ${WORK_MODE_LABELS[opportunity.work_mode]}`} /><Info icon={MapPin} value={location} /><Info icon={CalendarClock} value={`Deadline: ${formatDate(opportunity.application_deadline)}`} /></dl><p className="mt-3 text-xs text-[#d0d6e0]">{compensationLabel(opportunity.compensation)}</p><div className="mt-4 flex flex-wrap gap-2">{opportunity.required_skills?.slice(0, 4).map((skill) => <span key={skill.id} className="team-chip">{skill.name}</span>)}</div>{opportunity.eligibility ? <p className={`opportunity-eligibility is-${opportunity.eligibility.result} mt-4`}>{ELIGIBILITY_LABELS[opportunity.eligibility.result]}</p> : null}<Link to={`/opportunities/${opportunity.slug}`} className="team-button-primary mt-5 w-full">View Opportunity</Link></article>;
};
const Info = ({ icon: Icon, value }) => <div className="flex items-start gap-2"><Icon className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#62666d]" /><dd>{value}</dd></div>;
export default OpportunityCard;
