const domain = require("../../../shared/contracts/domain.json");

const toEnum = (values) =>
  Object.freeze(
    Object.fromEntries(
      values.map((value) => [value.toUpperCase().replace(/-/g, "_").replace(/[^A-Z0-9_]/g, "_"), value]),
    ),
  );

const contracts = Object.freeze({
  raw: domain,
  USER_ROLES: toEnum(domain.userRoles),
  PUBLIC_REGISTRATION_ROLES: Object.freeze([...domain.publicRegistrationRoles]),
  USER_STATUS: toEnum(domain.userStatuses),
  TASK_STATUS: toEnum(domain.taskStatuses),
  TASK_TYPES: toEnum(domain.taskTypes),
  TASK_PRIORITY: toEnum(domain.taskPriorities),
  SUBMISSION_TYPE: toEnum(domain.submissionTypes),
  QA_STATUS: toEnum(domain.qaStatuses),
  CLIENT_REVIEW_STATUS: toEnum(domain.clientReviewStatuses),
  PAYMENT_STATUS: toEnum(domain.paymentStatuses),
  REVIEW_TYPE: toEnum(domain.reviewTypes),
  NOTIFICATION_TYPES: toEnum(domain.notificationTypes),
  NOTIFICATION_STATUS: toEnum(domain.notificationStatuses),
  NOTIFICATION_PRIORITY: toEnum(domain.notificationPriorities),
  PROFILE_VISIBILITY: toEnum(domain.profileVisibilities),
  PROFILE_AVAILABILITY: toEnum(domain.profileAvailabilities),
  PROFILE_INTEREST: toEnum(domain.profileInterests),
  COLLABORATION_ROLE: toEnum(domain.collaborationRoles),
  COLLABORATION_COMMITMENT: toEnum(domain.collaborationCommitments),
  SKILL_PROFICIENCY: toEnum(domain.skillProficiencies),
  SKILL_CATEGORY: toEnum(domain.skillCategories),
  TEAM_VISIBILITY: toEnum(domain.teamVisibilities),
  TEAM_JOIN_POLICY: toEnum(domain.teamJoinPolicies),
  TEAM_STATUS: toEnum(domain.teamStatuses),
  TEAM_ROLE: toEnum(domain.teamRoles),
  TEAM_MEMBERSHIP_STATUS: toEnum(domain.teamMembershipStatuses),
  TEAM_INVITATION_STATUS: toEnum(domain.teamInvitationStatuses),
  TEAM_JOIN_REQUEST_STATUS: toEnum(domain.teamJoinRequestStatuses),
  TEAM_ACTIVITY_TYPES: toEnum(domain.teamActivityTypes),
  TEAM_OPENING_STATUS: toEnum(domain.teamOpeningStatuses),
  COLLABORATION_REQUEST_STATUS: toEnum(domain.collaborationRequestStatuses),
  HACKATHON_STATUS: toEnum(domain.hackathonStatuses),
  HACKATHON_MODE: toEnum(domain.hackathonModes),
  HACKATHON_VISIBILITY: toEnum(domain.hackathonVisibilities),
  HACKATHON_PARTICIPATION_STATUS: toEnum(domain.hackathonParticipationStatuses),
  HACKATHON_TEAM_STATUS: toEnum(domain.hackathonTeamStatuses),
  HACKATHON_SUBMISSION_STATUS: toEnum(domain.hackathonSubmissionStatuses),
  HACKATHON_REQUIREMENT_TYPE: toEnum(domain.hackathonRequirementTypes),
  HACKATHON_ACTIVITY_TYPES: toEnum(domain.hackathonActivityTypes),
  ORGANIZATION_TYPE: toEnum(domain.organizationTypes),
  ORGANIZATION_STATUS: toEnum(domain.organizationStatuses),
  ORGANIZATION_VERIFICATION: toEnum(domain.organizationVerificationStatuses),
  ORGANIZATION_MANAGEMENT_MODE: toEnum(domain.organizationManagementModes),
  ORGANIZATION_ROLE: toEnum(domain.organizationRoles),
  ORGANIZATION_MEMBERSHIP_STATUS: toEnum(domain.organizationMembershipStatuses),
  ORGANIZATION_INVITATION_STATUS: toEnum(domain.organizationInvitationStatuses),
  OPPORTUNITY_TYPE: toEnum(domain.opportunityTypes),
  OPPORTUNITY_STATUS: toEnum(domain.opportunityStatuses),
  WORK_MODE: toEnum(domain.workModes),
  EMPLOYMENT_TYPE: toEnum(domain.employmentTypes),
  ELIGIBILITY_RESULT: toEnum(domain.eligibilityResults),
  ELIGIBILITY_CHECK_RESULT: toEnum(domain.eligibilityCheckResults),
  APPLICATION_STATUS: toEnum(domain.applicationStatuses),
  COMPENSATION_PERIOD: toEnum(domain.compensationPeriods),
  OPPORTUNITY_SOURCE_TYPE: toEnum(domain.opportunitySourceTypes),
  OPPORTUNITY_APPLICATION_MODE: toEnum(domain.opportunityApplicationModes),
  NATIVE_APPLICATION_STAGE: toEnum(domain.nativeApplicationStages),
  APPLICATION_ACTIVITY_TYPE: toEnum(domain.applicationActivityTypes),
  NATIVE_APPLICATION_TRANSITIONS: Object.freeze(domain.nativeApplicationTransitions),
  TEAM_NOTIFICATION_TYPES: Object.freeze(Object.fromEntries(
    domain.notificationTypes.filter((value) => value.startsWith("team_")).map((value) => [value.toUpperCase(), value]),
  )),
  PROJECT_STATUS: toEnum(domain.projectStatuses),
  PROJECT_VISIBILITY: toEnum(domain.projectVisibilities),
  PROJECT_PARTICIPANT_ROLE: toEnum(domain.projectParticipantRoles),
  PROJECT_PARTICIPANT_STATUS: toEnum(domain.projectParticipantStatuses),
  PROJECT_TASK_STATUS: toEnum(domain.projectTaskStatuses),
  PROJECT_MILESTONE_STATUS: toEnum(domain.projectMilestoneStatuses),
  PROJECT_ACTIVITY_TYPES: toEnum(domain.projectActivityTypes),
  CONTRIBUTION_EVIDENCE_TYPES: toEnum(domain.contributionEvidenceTypes),
  CONTRIBUTION_VERIFICATION_LEVELS: toEnum(domain.contributionVerificationLevels),
  CONTRIBUTION_EVIDENCE_STATUSES: toEnum(domain.contributionEvidenceStatuses),
  CONTRIBUTION_EVIDENCE_ORIGINS: toEnum(domain.contributionEvidenceOrigins),
  REPOSITORY_PROVIDERS: toEnum(domain.repositoryProviders),
  REPOSITORY_VERIFICATION_STATUSES: toEnum(domain.repositoryVerificationStatuses),
  SHOWCASE_STATUSES: toEnum(domain.showcaseStatuses),
  PROJECT_NOTIFICATION_TYPES: Object.freeze(Object.fromEntries(
    domain.notificationTypes.filter((value) => value.startsWith("project_")).map((value) => [value.toUpperCase(), value]),
  )),
  PROJECT_STATE_TRANSITIONS: Object.freeze(domain.projectTransitions),
  PROJECT_TASK_TRANSITIONS: Object.freeze(domain.projectTaskTransitions),
  PROJECT_MILESTONE_TRANSITIONS: Object.freeze(domain.projectMilestoneTransitions),
  TASK_STATE_TRANSITIONS: Object.freeze(domain.taskTransitions),
});

const isContractValue = (group, value) =>
  Array.isArray(domain[group]) && domain[group].includes(value);

module.exports = {
  ...contracts,
  isContractValue,
};
