import { Filter, Loader2, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import TeamShell from "../components/teams/TeamShell";
import api from "../services/api";
import { apiError } from "../utils/teams";
import { formatDate } from "../utils/projects";

const ContributionsPage = () => {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [filters, setFilters] = useState({ type: "", verification: "", from: "", to: "" });
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get("/contributions/me", { params: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) }); setItems(response.data.data || []); setMeta(response.data.meta || {}); } catch (requestError) { setError(apiError(requestError)); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  return <TeamShell><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><header className="border-b border-[#23252a] pb-7"><p className="team-eyebrow">Your evidence history</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.045em]">Contributions</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#8a8f98]">A chronological record of facts and claims. Verification labels remain visible everywhere.</p></header><section className="mt-7 rounded-xl border border-[#23252a] bg-[#0f1011] p-4"><div className="flex items-center gap-2 text-sm font-medium"><Filter className="h-4 w-4 text-[#828fff]" /> Filters</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="Type" value={filters.type} onChange={(value) => setFilters({ ...filters, type: value })}><option value="">All types</option><option value="project_task_completion">Task completion</option><option value="github_commit">GitHub commit</option><option value="github_pull_request">Pull request</option><option value="external_link">External link</option></Select><Select label="Verification" value={filters.verification} onChange={(value) => setFilters({ ...filters, verification: value })}><option value="">All states</option><option value="internal_verified">Internal verified</option><option value="external_verified">External verified</option><option value="unverified">Unverified</option></Select><Field label="From" type="date" value={filters.from} onChange={(value) => setFilters({ ...filters, from: value })} /><Field label="To" type="date" value={filters.to} onChange={(value) => setFilters({ ...filters, to: value })} /></div></section>{loading ? <div className="flex py-24 justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#828fff]" /></div> : error ? <p className="py-12 text-sm text-red-300">{error}</p> : <section className="mt-6 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-[#23252a] bg-[#0f1011] p-5"><div className="flex flex-wrap items-center gap-2"><span className={`evidence-badge is-${item.verification}`}>{item.verification.replaceAll("_", " ")}</span><span className="team-chip">{item.type.replaceAll("_", " ")}</span></div><h2 className="mt-3 font-medium">{item.title}</h2><p className="mt-2 text-sm text-[#8a8f98]">{item.project?.name || "Project"} · {formatDate(item.occurred_at)}</p>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm text-[#828fff] hover:text-[#b7bdf8]">Inspect source</a> : null}</article>)}{!items.length ? <div className="py-20 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-[#62666d]" /><p className="mt-3 text-sm text-[#62666d]">No evidence matches these filters.</p></div> : null}<p className="pt-3 text-xs text-[#62666d]">{meta.total || 0} evidence records · neutral chronological order</p></section>}</main></TeamShell>;
};
const Select = ({ label, value, onChange, children }) => <label><span className="team-label">{label}</span><select className="team-input" value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>;
const Field = ({ label, value, onChange, ...props }) => <label><span className="team-label">{label}</span><input {...props} className="team-input" value={value} onChange={(event) => onChange(event.target.value)} /></label>;
export default ContributionsPage;
