import { Compass, FolderKanban, Loader2, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import ProjectCard from "../components/projects/ProjectCard";
import TeamShell from "../components/teams/TeamShell";
import api from "../services/api";
import { apiError } from "../utils/teams";

const ProjectsPage = () => {
  const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [role, setRole] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await api.get("/projects", { params: { ...(search.trim() ? { search: search.trim() } : {}), ...(status ? { status } : {}), ...(role ? { role } : {}), limit: 50 } }); setProjects(response.data.data || []); } catch (error) { toast.error(apiError(error, "Projects could not be loaded")); } finally { setLoading(false); } }, [role, search, status]);
  useEffect(() => { load(); }, [load]);
  return <TeamShell><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12"><header className="border-b border-[#23252a] pb-8"><p className="team-eyebrow">Project workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Build the work, not the dashboard.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#8a8f98] sm:text-base">Projects where you actively contribute or lead. Progress is based on real tasks and milestones,nothing decorative.</p></header><form onSubmit={(event) => { event.preventDefault(); load(); }} className="mt-8 grid gap-3 rounded-xl border border-[#23252a] bg-[#0f1011] p-3 sm:grid-cols-[minmax(0,1fr)_180px_180px_auto]"><label className="relative"><span className="sr-only">Search my projects</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-[#62666d]" /><input className="team-input pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects" /></label><label><span className="sr-only">Project status</span><select className="team-input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="planning">Planning</option><option value="active">Active</option><option value="completed">Completed</option></select></label><label><span className="sr-only">Project role</span><select className="team-input" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option><option value="lead">Lead</option><option value="contributor">Contributor</option></select></label><button className="team-button-secondary">Apply</button></form>{loading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#828fff]" aria-label="Loading projects" /></div> : projects.length ? <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3" aria-label="My projects">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}</section> : <section className="mt-6 rounded-xl border border-dashed border-[#34343a] bg-[#0f1011] px-5 py-14 text-center"><FolderKanban className="mx-auto h-7 w-7 text-[#62666d]" /><h2 className="mt-4 text-base font-medium">No projects in this view</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#8a8f98]">Projects begin inside Teams. Join a team or ask an owner or admin to create the next workspace.</p><Link to="/teams" className="team-button-primary mt-6"><Compass className="h-4 w-4" /> Open teams</Link></section>}</main></TeamShell>;
};

export default ProjectsPage;
