const skills = [
  ["javascript", "JavaScript", "languages", ["js", "ecmascript"]],
  ["typescript", "TypeScript", "languages", ["ts"]],
  ["python", "Python", "languages", ["python3"]],
  ["java", "Java", "languages", []],
  ["c-sharp", "C#", "languages", ["csharp", ".net c#"]],
  ["go", "Go", "languages", ["golang"]],
  ["rust", "Rust", "languages", []],
  ["react", "React", "frontend", ["reactjs", "react.js"]],
  ["next-js", "Next.js", "frontend", ["nextjs", "next"]],
  ["vue-js", "Vue.js", "frontend", ["vue", "vuejs"]],
  ["angular", "Angular", "frontend", ["angularjs"]],
  ["tailwind-css", "Tailwind CSS", "frontend", ["tailwind"]],
  ["html-css", "HTML & CSS", "frontend", ["html", "css", "html5", "css3"]],
  ["node-js", "Node.js", "backend", ["node", "nodejs"]],
  ["express-js", "Express.js", "backend", ["express", "expressjs"]],
  ["django", "Django", "backend", []],
  ["fastapi", "FastAPI", "backend", ["fast api"]],
  ["spring-boot", "Spring Boot", "backend", ["spring"]],
  ["graphql", "GraphQL", "backend", ["graphql api"]],
  ["rest-apis", "REST APIs", "backend", ["rest", "restful api"]],
  ["react-native", "React Native", "mobile", ["react-native"]],
  ["flutter", "Flutter", "mobile", ["dart flutter"]],
  ["ios-development", "iOS Development", "mobile", ["ios", "swiftui"]],
  ["android-development", "Android Development", "mobile", ["android", "kotlin android"]],
  ["postgresql", "PostgreSQL", "database", ["postgres", "psql"]],
  ["mysql", "MySQL", "database", []],
  ["mongodb", "MongoDB", "database", ["mongo"]],
  ["supabase", "Supabase", "database", []],
  ["redis", "Redis", "database", []],
  ["machine-learning", "Machine Learning", "data-ai", ["ml"]],
  ["data-analysis", "Data Analysis", "data-ai", ["analytics"]],
  ["generative-ai", "Generative AI", "data-ai", ["genai", "llm"]],
  ["aws", "Amazon Web Services", "cloud-devops", ["amazon web services"]],
  ["azure", "Microsoft Azure", "cloud-devops", ["azure cloud"]],
  ["google-cloud", "Google Cloud", "cloud-devops", ["gcp"]],
  ["docker", "Docker", "cloud-devops", ["containers"]],
  ["kubernetes", "Kubernetes", "cloud-devops", ["k8s"]],
  ["ci-cd", "CI/CD", "cloud-devops", ["continuous integration"]],
  ["figma", "Figma", "design", []],
  ["ui-ux-design", "UI/UX Design", "design", ["ux", "ui design", "product design"]],
  ["product-management", "Product Management", "product", ["product manager"]],
  ["project-management", "Project Management", "product", ["project manager"]],
  ["automated-testing", "Automated Testing", "quality", ["test automation", "qa automation"]],
  ["technical-writing", "Technical Writing", "collaboration", ["documentation"]],
  ["mentoring", "Mentoring", "collaboration", ["coaching"]],
  ["git", "Git", "cloud-devops", ["version control"]],
  ["github", "GitHub", "collaboration", ["github actions", "github workflows"]],
  ["cybersecurity", "Cybersecurity", "quality", ["information security", "appsec"]],
].map(([slug, name, category, aliases]) => ({ slug, name, normalized_name: name.toLowerCase(), category, aliases, is_active: true }));

module.exports = skills;
