const {
  escapeHtml,
  renderBulletList,
  renderDetailRows,
  renderEmailShell,
  renderInfoCard,
} = require("./layout");

const formatDateLabel = (dateValue) => {
  if (!dateValue) return "";
  const date = new Date(`${dateValue}T00:00:00`);
  if (Number.isNaN(date.getTime())) return String(dateValue);
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
};

const formatDateTimeLabel = (dateValue) => {
  if (!dateValue) return "";
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return String(dateValue);
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short",
  }).format(date);
};

const formatCurrency = (amount, currency = "USD") => {
  const numericAmount = Number(amount || 0);
  try {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
      maximumFractionDigits: 2,
    }).format(numericAmount);
  } catch (error) {
    return `${currency} ${numericAmount.toFixed(2)}`;
  }
};

const getName = (value, fallback) => {
  const normalized = String(value || "").trim();
  return normalized || fallback;
};

const buildNewsletterThanksEmail = ({ email, appUrl }) => ({
  subject: "Thanks for subscribing to TaskNexus updates",
  text: [
    `Hi ${email},`,
    "",
    "Thanks for subscribing to TaskNexus updates.",
    "We will send practical notes, delivery ideas, and useful product updates.",
    "",
    `Visit TaskNexus: ${appUrl}`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "Thanks for subscribing to TaskNexus updates.",
    eyebrow: "Newsletter",
    title: "Thanks for subscribing",
    intro:
      "You are on the list. We will keep the emails useful, clear, and worth opening.",
    bodyHtml: `
      <p style="margin:0;color:#334155;font-size:15px;line-height:1.8;">
        We have added <strong>${escapeHtml(email)}</strong> to our blog and product update list. Expect practical ideas around delivery systems, operations, and managed execution.
      </p>
      ${renderInfoCard({
        title: "What you can expect",
        body: renderBulletList([
          "Short operational playbooks and practical workflow ideas.",
          "Product and service updates from TaskNexus.",
          "Noisy marketing is not the goal here. Useful communication is.",
        ]),
      })}
    `,
    cta: {
      href: `${appUrl}/blog`,
      label: "Read the blog",
    },
    footerLines: [
      "You received this email because you subscribed on the TaskNexus blog.",
      "TaskNexus focuses on managed delivery, operations, and execution support.",
    ],
  }),
});

const buildNewsletterAdminEmail = ({ email, subscribedAt }) => ({
  subject: "New TaskNexus newsletter subscriber",
  text: [
    "New newsletter subscriber received.",
    `Email: ${email}`,
    `Subscribed at: ${formatDateTimeLabel(subscribedAt)}`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "New newsletter subscriber received.",
    eyebrow: "Admin Alert",
    title: "New newsletter subscriber",
    intro: "A new email address subscribed from the public blog page.",
    bodyHtml: renderDetailRows([
      { label: "Email", value: email },
      { label: "Source", value: "blog" },
      { label: "Subscribed at", value: formatDateTimeLabel(subscribedAt) },
    ]),
    footerLines: [
      "This alert was generated by the TaskNexus public newsletter flow.",
    ],
  }),
});

const buildServiceBookingCustomerEmail = ({ booking, appUrl }) => ({
  subject: `Booking confirmed: ${booking.service_snapshot?.name || booking.service_slug}`,
  text: [
    `Hi ${booking.full_name},`,
    "",
    "Your TaskNexus booking is confirmed.",
    `Service: ${booking.service_snapshot?.name || booking.service_slug}`,
    `Booking ID: ${booking.booking_id}`,
    `Session ID: ${booking.session_id}`,
    `Preferred date: ${formatDateLabel(booking.preferred_date)}`,
    `Preferred time: ${booking.preferred_time} (${booking.timezone})`,
    "",
    `Review services: ${appUrl}/services`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "Your TaskNexus booking is confirmed.",
    eyebrow: "Service Booking",
    title: "Your session is confirmed",
    intro:
      "Thanks for booking with TaskNexus. We have recorded your session details and attached a confirmation PDF for reference.",
    bodyHtml: `
      <p style="margin:0;color:#334155;font-size:15px;line-height:1.8;">
        Hi <strong>${escapeHtml(booking.full_name)}</strong>, your booking for <strong>${escapeHtml(
          booking.service_snapshot?.name || booking.service_slug
        )}</strong> is confirmed.
      </p>
      ${renderDetailRows([
        { label: "Booking ID", value: booking.booking_id },
        { label: "Session ID", value: booking.session_id },
        { label: "Service", value: booking.service_snapshot?.name || booking.service_slug },
        { label: "Preferred date", value: formatDateLabel(booking.preferred_date) },
        { label: "Preferred time", value: `${booking.preferred_time} (${booking.timezone})` },
        { label: "Email", value: booking.email },
        { label: "Phone", value: booking.phone || "Not provided" },
      ])}
      ${renderInfoCard({
        title: "Included in your confirmation",
        body: renderBulletList([
          "A branded confirmation PDF is attached to this email.",
          "We will use the submitted details to prepare the session context.",
          booking.notes ? `Notes received: ${booking.notes}` : "No additional notes were submitted.",
        ]),
        accent: "#22c55e",
      })}
    `,
    cta: {
      href: `${appUrl}/services`,
      label: "View services",
    },
    footerLines: [
      "Reply to this email if you need to adjust your submitted details.",
      "Keep the attached PDF for your booking and session reference.",
    ],
  }),
});

const buildServiceBookingAdminEmail = ({ booking }) => ({
  subject: `New service booking: ${booking.service_snapshot?.name || booking.service_slug}`,
  text: [
    "New public service booking received.",
    `Customer: ${booking.full_name}`,
    `Email: ${booking.email}`,
    `Service: ${booking.service_snapshot?.name || booking.service_slug}`,
    `Booking ID: ${booking.booking_id}`,
    `Session ID: ${booking.session_id}`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "New public service booking received.",
    eyebrow: "Admin Alert",
    title: "New service booking",
    intro: "A public visitor submitted and confirmed a service booking.",
    bodyHtml: `
      ${renderDetailRows([
        { label: "Customer", value: booking.full_name },
        { label: "Email", value: booking.email },
        { label: "Phone", value: booking.phone || "Not provided" },
        { label: "Service", value: booking.service_snapshot?.name || booking.service_slug },
        { label: "Booking ID", value: booking.booking_id },
        { label: "Session ID", value: booking.session_id },
        { label: "Preferred date", value: formatDateLabel(booking.preferred_date) },
        { label: "Preferred time", value: `${booking.preferred_time} (${booking.timezone})` },
        { label: "Submitted at", value: formatDateTimeLabel(booking.created_at) },
      ])}
      ${
        booking.notes
          ? renderInfoCard({
              title: "Notes",
              body: escapeHtml(booking.notes),
              accent: "#f59e0b",
            })
          : ""
      }
    `,
    footerLines: [
      "This alert was generated by the TaskNexus public service booking flow.",
    ],
  }),
});

const buildSupportJarThankYouEmail = ({ contribution, appUrl }) => ({
  subject: "Super thanks from TaskNexus",
  text: [
    `Hi ${contribution.full_name},`,
    "",
    `Thank you for your support. We received ${formatCurrency(contribution.amount, contribution.currency)} in the TaskNexus support jar.`,
    "",
    `Visit TaskNexus: ${appUrl}`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "Thank you for supporting TaskNexus.",
    eyebrow: "Support Jar",
    title: "Super thanks",
    intro:
      "Your support helps us keep building sharper systems, cleaner delivery, and better experiences inside TaskNexus.",
    bodyHtml: `
      <p style="margin:0;color:#334155;font-size:15px;line-height:1.8;">
        Hi <strong>${escapeHtml(contribution.full_name)}</strong>, thank you for contributing <strong>${escapeHtml(
          formatCurrency(contribution.amount, contribution.currency)
        )}</strong> to the TaskNexus support jar.
      </p>
      ${renderInfoCard({
        title: "What this means to us",
        body: renderBulletList([
          "It helps us keep improving the platform and public resources.",
          "It is a direct signal that the work is useful.",
          contribution.message ? `Your message: ${contribution.message}` : "Your support came through loud and clear.",
        ]),
        accent: "#f59e0b",
      })}
    `,
    cta: {
      href: appUrl,
      label: "Visit TaskNexus",
    },
    footerLines: [
      "We appreciate the support and the trust behind it.",
      "This is an automated thank-you email from TaskNexus.",
    ],
  }),
});

const buildSupportJarAdminEmail = ({ contribution }) => ({
  subject: "New TaskNexus support jar contribution",
  text: [
    "New support jar contribution received.",
    `Name: ${contribution.full_name}`,
    `Email: ${contribution.email}`,
    `Amount: ${formatCurrency(contribution.amount, contribution.currency)}`,
  ].join("\n"),
  html: renderEmailShell({
    previewText: "New TaskNexus support jar contribution.",
    eyebrow: "Admin Alert",
    title: "New support contribution",
    intro: "A public visitor contributed to the TaskNexus support jar.",
    bodyHtml: `
      ${renderDetailRows([
        { label: "Name", value: contribution.full_name },
        { label: "Email", value: contribution.email },
        { label: "Amount", value: formatCurrency(contribution.amount, contribution.currency) },
        { label: "Submitted at", value: formatDateTimeLabel(contribution.created_at) },
      ])}
      ${
        contribution.message
          ? renderInfoCard({
              title: "Supporter message",
              body: escapeHtml(contribution.message),
              accent: "#22c55e",
            })
          : ""
      }
    `,
    footerLines: [
      "This alert was generated by the TaskNexus support jar public flow.",
    ],
  }),
});

module.exports = {
  buildNewsletterAdminEmail,
  buildNewsletterThanksEmail,
  buildServiceBookingAdminEmail,
  buildServiceBookingCustomerEmail,
  buildSupportJarAdminEmail,
  buildSupportJarThankYouEmail,
  formatCurrency,
  formatDateLabel,
  formatDateTimeLabel,
  getName,
};
