/**
 * Application-wide constants
 * Centralized configuration for business rules and enums
 */

const {
  USER_ROLES,
  PUBLIC_REGISTRATION_ROLES,
  USER_STATUS,
  TASK_STATUS,
  TASK_TYPES,
  TASK_PRIORITY,
  SUBMISSION_TYPE,
  QA_STATUS,
  CLIENT_REVIEW_STATUS,
  PAYMENT_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_STATUS,
  NOTIFICATION_PRIORITY,
  REVIEW_TYPE,
  TASK_STATE_TRANSITIONS,
} = require("../contracts/domain");

// Business Rules
const BUSINESS_RULES = {
  PLATFORM_COMMISSION:
    parseFloat(process.env.PLATFORM_COMMISSION_PERCENTAGE) || 15,
  DEFAULT_REVISION_LIMIT: parseInt(process.env.DEFAULT_REVISION_LIMIT) || 2,
  QA_REVIEW_SLA_HOURS: parseInt(process.env.QA_REVIEW_SLA_HOURS) || 12,
  DISPUTE_RESOLUTION_SLA_HOURS:
    parseInt(process.env.DISPUTE_RESOLUTION_SLA_HOURS) || 48,
  DEADLINE_WARNING_HOURS: 24,
  REVISION_DEADLINE_EXTENSION_HOURS: 48,
  MISSED_DEADLINE_PENALTY: 5,
  SUSPENSION_THRESHOLD_MISSED_DEADLINES: 3,
  MIN_PERFORMANCE_SCORE: 0,
  MAX_PERFORMANCE_SCORE: 100,
  MIN_RATING: 1,
  MAX_RATING: 5,
  PASSWORD_MIN_LENGTH: 8,
  MAX_FILE_SIZE: parseInt(process.env.MAX_FILE_SIZE) || 10485760, // 10MB
  ALLOWED_FILE_TYPES: [
    "image/jpeg",
    "image/png",
    "image/gif",
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "video/mp4",
    "video/quicktime",
    "application/zip",
  ],
};

// Assignment scoring weights
const ASSIGNMENT_WEIGHTS = {
  PERFORMANCE_SCORE: 0.4,
  SKILL_MATCH: 0.3,
  AVAILABILITY: 0.2,
  COMPLETION_RATE: 0.1,
};

// Performance score calculation weights
const PERFORMANCE_WEIGHTS = {
  ON_TIME_COMPLETION: 0.4,
  FIRST_TIME_APPROVAL: 0.3,
  CLIENT_SATISFACTION: 0.2,
  QA_PASS_RATE: 0.1,
};

// Error codes
const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_ERROR: "DUPLICATE_ERROR",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

module.exports = {
  USER_ROLES,
  PUBLIC_REGISTRATION_ROLES,
  USER_STATUS,
  TASK_STATUS,
  TASK_TYPES,
  TASK_PRIORITY,
  SUBMISSION_TYPE,
  QA_STATUS,
  CLIENT_REVIEW_STATUS,
  PAYMENT_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_STATUS,
  NOTIFICATION_PRIORITY,
  REVIEW_TYPE,
  BUSINESS_RULES,
  TASK_STATE_TRANSITIONS,
  ASSIGNMENT_WEIGHTS,
  PERFORMANCE_WEIGHTS,
  ERROR_CODES,
};
